#pragma config(Sensor, in1,    left_intake,    sensorPotentiometer)
#pragma config(Sensor, in2,    right_intake,   sensorPotentiometer)
#pragma config(Motor,  port2,           Left,          tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           Right,         tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

	int desired_left_pot = SensorValue[left_intake];
	int desired_right_pot = SensorValue[right_intake];

	/*
	forever {

	if the left pot is less than desired pot value
	then power motor upward

	desired val += (vexrt ch3 * 0.1)

	}


	*/
	float joystick_c = 4;
	float motor_speed_c = 0.07;
	int current_left_error;
	int current_right_error;
	int pot_tolerance = 2;
	while(true){
		wait1Msec(1);
		desired_left_pot += vexRT[Btn8L]* joystick_c -vexRT[Btn8R]* joystick_c;
		desired_right_pot += vexRT[Btn8L]* joystick_c - vexRT[Btn8R]* joystick_c;
		current_left_error = desired_left_pot - SensorValue(left_intake);
		if(abs(current_left_error) > pot_tolerance){
			motor[Left] = -1 * current_left_error * motor_speed_c;
		}
		current_right_error = desired_right_pot - SensorValue(right_intake);
		if(abs(current_right_error) > pot_tolerance){
			motor[Right] = -1 * current_right_error * motor_speed_c;
		}
	}
}
