#pragma config(Sensor, in1,    left_pot,       sensorPotentiometer)
#pragma config(Sensor, in2,    right_pot,      sensorPotentiometer)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	float min_left_pot_val = SensorValue(left_pot);
	float min_right_pot_val = SensorValue(right_pot);
	while(true){
		motor[port5] = vexRT[Ch3];
		motor[port4] = -1 * vexRT[Ch3];
		motor[port3] = vexRT[Ch3];
		motor[port2] = -1 * vexRT[Ch3];

		motor[port7] = -1 * vexRT[Ch3];
		motor[port6] = vexRT[Ch3];

		if(min_left_pot_val > SensorValue(left_pot) || vexRT[Ch2] < 0){
			motor[port8] = -1 * vexRT[Ch2];
		} else {
			motor[port8] = 30;
		}

		if(min_right_pot_val > SensorValue(right_pot) || vexRT[Ch2] < 0){
			motor[port9] = vexRT[Ch2];
		} else {
			motor[port9] = -30;
		}
	}

}
